### ISSUE TITLE
Getting this error while installing packages

### ISSUE THREAD

**Issue by Harshdeshmukh** [app-generator/react-datta-able#2]
<img width="519" alt="Screenshot 2022-03-03 150539" src="https://user-images.githubusercontent.com/47944639/156537690-48bb76c4-c500-4025-9da4-2481d8d9deb8.png">

**Comment by Harshdeshmukh** [comment]
> Hello @Harshdeshmukh
> 
> Please use NodejS `14.x` version.

my Current Node Version is 14.17.5

**Comment by app-generator** [comment]
Hello @Harshdeshmukh 

Try to execute this set up: 

- activate `14.15.0` via NVM or classic install
- Use Yarn as package manager
  - `yarn`
  - `yarn start` 

Just execute the above set up on a Windows machine and was ok. 
Let us know your progress

**Comment by app-generator** [comment]
Hello @Harshdeshmukh 

Regarding this issue, let us know if you need further assistance.
